POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIiLCJpZCI6IjYxYjMyZTIwZTJmNDhlMDFjY2FhYzM0YyIsImlhdCI6MTYzOTQ3NzMwOH0.x5LHFLyHQCKoYf5n-oLUcPh9wmNb55KaN0mXseE01gg

{ 
  "title": "titteli",
  "author": "authori",
  "url": "urli",
  "likes": 100,
  "userId": "61b32e20e2f48e01ccaac34c"
}